# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import invigilator_pb2 as invigilator__pb2


class InvigilatorWebStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UpdateExam = channel.unary_unary(
        '/invigilator.InvigilatorWeb/UpdateExam',
        request_serializer=invigilator__pb2.HoldExamRequest.SerializeToString,
        response_deserializer=invigilator__pb2.CommonGetResponse.FromString,
        )
    self.DeleteExam = channel.unary_unary(
        '/invigilator.InvigilatorWeb/DeleteExam',
        request_serializer=invigilator__pb2.CommonGetRequest.SerializeToString,
        response_deserializer=invigilator__pb2.CommonGetResponse.FromString,
        )
    self.GetExams = channel.unary_unary(
        '/invigilator.InvigilatorWeb/GetExams',
        request_serializer=invigilator__pb2.CommonGetRequest.SerializeToString,
        response_deserializer=invigilator__pb2.ExamResponse.FromString,
        )
    self.GetPredicts = channel.unary_unary(
        '/invigilator.InvigilatorWeb/GetPredicts',
        request_serializer=invigilator__pb2.GetPredictRequest.SerializeToString,
        response_deserializer=invigilator__pb2.GetPredictResponse.FromString,
        )
    self.StreamInvigilation = channel.unary_stream(
        '/invigilator.InvigilatorWeb/StreamInvigilation',
        request_serializer=invigilator__pb2.MetaData.SerializeToString,
        response_deserializer=invigilator__pb2.StreamInvigilationResponse.FromString,
        )


class InvigilatorWebServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UpdateExam(self, request, context):
    """return examId
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteExam(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetExams(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPredicts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamInvigilation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InvigilatorWebServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UpdateExam': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateExam,
          request_deserializer=invigilator__pb2.HoldExamRequest.FromString,
          response_serializer=invigilator__pb2.CommonGetResponse.SerializeToString,
      ),
      'DeleteExam': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteExam,
          request_deserializer=invigilator__pb2.CommonGetRequest.FromString,
          response_serializer=invigilator__pb2.CommonGetResponse.SerializeToString,
      ),
      'GetExams': grpc.unary_unary_rpc_method_handler(
          servicer.GetExams,
          request_deserializer=invigilator__pb2.CommonGetRequest.FromString,
          response_serializer=invigilator__pb2.ExamResponse.SerializeToString,
      ),
      'GetPredicts': grpc.unary_unary_rpc_method_handler(
          servicer.GetPredicts,
          request_deserializer=invigilator__pb2.GetPredictRequest.FromString,
          response_serializer=invigilator__pb2.GetPredictResponse.SerializeToString,
      ),
      'StreamInvigilation': grpc.unary_stream_rpc_method_handler(
          servicer.StreamInvigilation,
          request_deserializer=invigilator__pb2.MetaData.FromString,
          response_serializer=invigilator__pb2.StreamInvigilationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'invigilator.InvigilatorWeb', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
