# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import signUpIn_pb2 as signUpIn__pb2


class SignUpInStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SignUp = channel.unary_unary(
        '/signUpIn.SignUpIn/SignUp',
        request_serializer=signUpIn__pb2.SignUpRequest.SerializeToString,
        response_deserializer=signUpIn__pb2.SignUpInResponse.FromString,
        )
    self.SignIn = channel.unary_unary(
        '/signUpIn.SignUpIn/SignIn',
        request_serializer=signUpIn__pb2.SignInRequest.SerializeToString,
        response_deserializer=signUpIn__pb2.SignUpInResponse.FromString,
        )
    self.SignOut = channel.unary_unary(
        '/signUpIn.SignUpIn/SignOut',
        request_serializer=signUpIn__pb2.SignOutRequest.SerializeToString,
        response_deserializer=signUpIn__pb2.CommonGetResponse.FromString,
        )
    self.RefreshToken = channel.unary_unary(
        '/signUpIn.SignUpIn/RefreshToken',
        request_serializer=signUpIn__pb2.CommonGetRequest.SerializeToString,
        response_deserializer=signUpIn__pb2.SignUpInResponse.FromString,
        )


class SignUpInServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SignUp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignIn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignOut(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RefreshToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SignUpInServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SignUp': grpc.unary_unary_rpc_method_handler(
          servicer.SignUp,
          request_deserializer=signUpIn__pb2.SignUpRequest.FromString,
          response_serializer=signUpIn__pb2.SignUpInResponse.SerializeToString,
      ),
      'SignIn': grpc.unary_unary_rpc_method_handler(
          servicer.SignIn,
          request_deserializer=signUpIn__pb2.SignInRequest.FromString,
          response_serializer=signUpIn__pb2.SignUpInResponse.SerializeToString,
      ),
      'SignOut': grpc.unary_unary_rpc_method_handler(
          servicer.SignOut,
          request_deserializer=signUpIn__pb2.SignOutRequest.FromString,
          response_serializer=signUpIn__pb2.CommonGetResponse.SerializeToString,
      ),
      'RefreshToken': grpc.unary_unary_rpc_method_handler(
          servicer.RefreshToken,
          request_deserializer=signUpIn__pb2.CommonGetRequest.FromString,
          response_serializer=signUpIn__pb2.SignUpInResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'signUpIn.SignUpIn', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
