# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signUpIn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signUpIn.proto',
  package='signUpIn',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0esignUpIn.proto\x12\x08signUpIn\"#\n\x10\x43ommonGetRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\".\n\x11\x43ommonGetResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"U\n\rSignUpRequest\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"R\n\x10SignUpInResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0f\n\x07\x61uthKey\x18\x03 \x01(\t\x12\x12\n\nrefreshKey\x18\x04 \x01(\t\"0\n\rSignInRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\x0eSignOutRequest\x12\x0f\n\x07\x61uthKey\x18\x01 \x01(\t\x12\x12\n\nrefreshKey\x18\x02 \x01(\t2\x92\x02\n\x08SignUpIn\x12=\n\x06SignUp\x12\x17.signUpIn.SignUpRequest\x1a\x1a.signUpIn.SignUpInResponse\x12=\n\x06SignIn\x12\x17.signUpIn.SignInRequest\x1a\x1a.signUpIn.SignUpInResponse\x12@\n\x07SignOut\x12\x18.signUpIn.SignOutRequest\x1a\x1b.signUpIn.CommonGetResponse\x12\x46\n\x0cRefreshToken\x12\x1a.signUpIn.CommonGetRequest\x1a\x1a.signUpIn.SignUpInResponseb\x06proto3')
)




_COMMONGETREQUEST = _descriptor.Descriptor(
  name='CommonGetRequest',
  full_name='signUpIn.CommonGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='signUpIn.CommonGetRequest.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=63,
)


_COMMONGETRESPONSE = _descriptor.Descriptor(
  name='CommonGetResponse',
  full_name='signUpIn.CommonGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='signUpIn.CommonGetResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='signUpIn.CommonGetResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=111,
)


_SIGNUPREQUEST = _descriptor.Descriptor(
  name='SignUpRequest',
  full_name='signUpIn.SignUpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstName', full_name='signUpIn.SignUpRequest.firstName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='signUpIn.SignUpRequest.lastName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='signUpIn.SignUpRequest.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='signUpIn.SignUpRequest.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=198,
)


_SIGNUPINRESPONSE = _descriptor.Descriptor(
  name='SignUpInResponse',
  full_name='signUpIn.SignUpInResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='signUpIn.SignUpInResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='signUpIn.SignUpInResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authKey', full_name='signUpIn.SignUpInResponse.authKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refreshKey', full_name='signUpIn.SignUpInResponse.refreshKey', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=282,
)


_SIGNINREQUEST = _descriptor.Descriptor(
  name='SignInRequest',
  full_name='signUpIn.SignInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='signUpIn.SignInRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='signUpIn.SignInRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=332,
)


_SIGNOUTREQUEST = _descriptor.Descriptor(
  name='SignOutRequest',
  full_name='signUpIn.SignOutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authKey', full_name='signUpIn.SignOutRequest.authKey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refreshKey', full_name='signUpIn.SignOutRequest.refreshKey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=387,
)

DESCRIPTOR.message_types_by_name['CommonGetRequest'] = _COMMONGETREQUEST
DESCRIPTOR.message_types_by_name['CommonGetResponse'] = _COMMONGETRESPONSE
DESCRIPTOR.message_types_by_name['SignUpRequest'] = _SIGNUPREQUEST
DESCRIPTOR.message_types_by_name['SignUpInResponse'] = _SIGNUPINRESPONSE
DESCRIPTOR.message_types_by_name['SignInRequest'] = _SIGNINREQUEST
DESCRIPTOR.message_types_by_name['SignOutRequest'] = _SIGNOUTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonGetRequest = _reflection.GeneratedProtocolMessageType('CommonGetRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMMONGETREQUEST,
  __module__ = 'signUpIn_pb2'
  # @@protoc_insertion_point(class_scope:signUpIn.CommonGetRequest)
  ))
_sym_db.RegisterMessage(CommonGetRequest)

CommonGetResponse = _reflection.GeneratedProtocolMessageType('CommonGetResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMMONGETRESPONSE,
  __module__ = 'signUpIn_pb2'
  # @@protoc_insertion_point(class_scope:signUpIn.CommonGetResponse)
  ))
_sym_db.RegisterMessage(CommonGetResponse)

SignUpRequest = _reflection.GeneratedProtocolMessageType('SignUpRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUPREQUEST,
  __module__ = 'signUpIn_pb2'
  # @@protoc_insertion_point(class_scope:signUpIn.SignUpRequest)
  ))
_sym_db.RegisterMessage(SignUpRequest)

SignUpInResponse = _reflection.GeneratedProtocolMessageType('SignUpInResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUPINRESPONSE,
  __module__ = 'signUpIn_pb2'
  # @@protoc_insertion_point(class_scope:signUpIn.SignUpInResponse)
  ))
_sym_db.RegisterMessage(SignUpInResponse)

SignInRequest = _reflection.GeneratedProtocolMessageType('SignInRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNINREQUEST,
  __module__ = 'signUpIn_pb2'
  # @@protoc_insertion_point(class_scope:signUpIn.SignInRequest)
  ))
_sym_db.RegisterMessage(SignInRequest)

SignOutRequest = _reflection.GeneratedProtocolMessageType('SignOutRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNOUTREQUEST,
  __module__ = 'signUpIn_pb2'
  # @@protoc_insertion_point(class_scope:signUpIn.SignOutRequest)
  ))
_sym_db.RegisterMessage(SignOutRequest)



_SIGNUPIN = _descriptor.ServiceDescriptor(
  name='SignUpIn',
  full_name='signUpIn.SignUpIn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=390,
  serialized_end=664,
  methods=[
  _descriptor.MethodDescriptor(
    name='SignUp',
    full_name='signUpIn.SignUpIn.SignUp',
    index=0,
    containing_service=None,
    input_type=_SIGNUPREQUEST,
    output_type=_SIGNUPINRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SignIn',
    full_name='signUpIn.SignUpIn.SignIn',
    index=1,
    containing_service=None,
    input_type=_SIGNINREQUEST,
    output_type=_SIGNUPINRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SignOut',
    full_name='signUpIn.SignUpIn.SignOut',
    index=2,
    containing_service=None,
    input_type=_SIGNOUTREQUEST,
    output_type=_COMMONGETRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RefreshToken',
    full_name='signUpIn.SignUpIn.RefreshToken',
    index=3,
    containing_service=None,
    input_type=_COMMONGETREQUEST,
    output_type=_SIGNUPINRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGNUPIN)

DESCRIPTOR.services_by_name['SignUpIn'] = _SIGNUPIN

# @@protoc_insertion_point(module_scope)
